print load and unload envs like direnv
jdx/rtx pull request #786
Opened 2023-08-09 12:40 UTC by dfang

close #733

@jdxcode  maybe add an ENV to toggle this, like `RTX_ENV_LOAD_MESSAGE` or else?

2023-08-09 15:29 UTC, jdxcode requested changes

2023-08-09 15:29 UTC, jdxcode commented on src/hook_env.rs
> +                    info!("load env {}={}", k, v);
This is not the right place for this code

2023-08-09 16:07 UTC, jdx commented on src/hook_env.rs
> +                    info!("load env {}={}", k, v);
this function is just a utility function to build the change list, it shouldn't be displaying any UI, that should be in the command

2023-08-10 01:28 UTC, jdxcode commented on src/cli/hook_env.rs
> +        for patch in patches.iter() {
This should go inside of display_status() I think

2023-08-17 15:13 UTC, jdx commented on src/cli/hook_env.rs
> +        self.display_env_load_unload_status(config, ts);
can we pass `patches` through so we don't need to regenerate it?

2023-08-17 15:14 UTC, jdx commented on src/cli/hook_env.rs
> +        self.display_env_load_unload_status(config, ts);
keep the extraction that added `get_patches()` though, that's a useful refactor

2023-08-17 15:15 UTC, jdxcode commented on src/cli/hook_env.rs
> +                eprintln!("Error: {}", error);
don't ever say "error" unless something actually failed, this should say "warn" and use `warn!()`

2023-08-17 15:17 UTC, jdxcode commented on src/cli/hook_env.rs
> +                    info!("load env {}={}", k, v);
don't display the value, the value could be massive. I think we should use direnv's syntax here for `+ADDED` `-REMOVED` `~CHANGED` https://github.com/direnv/direnv/blob/517e9f5b4159db2ce63695e4f51ca7b38b867876/internal/cmd/cmd_export.go#L102

2023-08-17 15:18 UTC, jdxcode commented on src/cli/hook_env.rs
> +                    info!("load env {}={}", k, v);
also show everything on one line

2023-11-27 23:50 UTC, closed without merging