skip redownload if file exists
jdx/rtx pull request #827
Opened 2023-08-21 16:06 UTC by dfang

skip redownload if file exists for go, bun, deno, java
for node and python, they are controlled by NODE_BUILD_BUILD_PATH and PYTHON_BUILD_BUILD_PATH

2023-08-21 16:26 UTC, jdxcode requested changes

2023-08-21 16:26 UTC, jdxcode commented on src/plugins/core/java.rs
> +            hash::ensure_checksum_sha256(&tarball_path, &m.sha256)?;
we need to still check the checksum to see if it is valid, if not we should redownload it. For languages that do not support checksums we should always redownload.

2023-08-21 16:39 UTC, dfang commented on src/plugins/core/java.rs
> +            hash::ensure_checksum_sha256(&tarball_path, &m.sha256)?;
currently go and java plugin have checksum support, deno and bun are downloading from GitHub,  bun has SHASUMS256.txt in release assets, but deno doesn't

2023-08-21 16:41 UTC, dfang commented on src/plugins/core/java.rs
> +            hash::ensure_checksum_sha256(&tarball_path, &m.sha256)?;
If the network is not smooth, re-downloading might be very slow. I will try to add checksum support or env like RTX_GO_SKIP_CHECKSUM

2023-08-22 01:57 UTC, dfang commented on src/tool.rs
> +        // let _ = remove_all_with_warning(tv.download_path());
this applies to all plugins? not only core plugins?

2023-11-27 23:50 UTC, closed without merging