add support for macos integration
jdx/rtx pull request #858
Opened 2023-08-28 12:00 UTC by roele

This is first rough draft. Which works with with `sudo`, what i currently don't like yet is that using `sudo` installs the JDK with `root` as the owner which currently fails with an unspecific error (since installation is removed before the symlink remove is attempted). This might potentially lead to other issues as well.

```
$ sudo env RTX_JAVA_MACOS_INTEGRATION=true .bin/rtx install java@corretto-20.0.2.10.1
$ /usr/libexec/java_home -V
$ sudo env .bin/rtx uninstall java@corretto-20.0.2.10.1
$ /usr/libexec/java_home -V
```

2023-08-28 12:57 UTC, jdx requested changes

2023-08-28 12:57 UTC, jdx commented on docs/java.md
> +sudo RTX_JAVA_MACOS_INTEGRATION=true rtx install java@openjdk-20
I don't think we can do this. It's going to create a bunch of root-owned files in your home directory that are going to cause problems later.

2023-08-28 13:04 UTC, jdx commented on docs/java.md
> +sudo RTX_JAVA_MACOS_INTEGRATION=true rtx install java@openjdk-20
what we could do is create the files with `chown $SUDO_USER:$SUDO_GROUP` if it's running under sudo. However I think rtx just creates too many files in too many places for us to be able to do that reliably.

2023-08-28 13:08 UTC, jdx commented on docs/java.md
> +sudo RTX_JAVA_MACOS_INTEGRATION=true rtx install java@openjdk-20
I think the safest thing to do would be something like this instead:

```
warn!("to integrate java_home with this install, run `sudo ln -s ~/.local/share/rtx/... /Library/Java/JavaVirtualMachines`");
```

just print out a command with the ln instruction they need to run under sudo if it doesn't already exist

2023-08-28 13:16 UTC, roele commented on docs/java.md
> +sudo RTX_JAVA_MACOS_INTEGRATION=true rtx install java@openjdk-20
I agree, having root owned files is definitely a no-go. Maybe your proposal to show an info message after the installation with the command to create the symlink manually (if the vendor supports it) is a better approach.

In this case we also might not need to environment variable to trigger the feature.

Will adapt the PR accordingly later today...

2023-08-28 13:19 UTC, roele commented on src/plugins/core/java.rs
> +        if tv.install_path().join("Contents/Home").exists() {
@jdx since we are removing the folding i assume this is required to ensure that already installed tools would continue to work. is this correct?

2023-08-28 13:26 UTC, jdx commented on src/plugins/core/java.rs
> +        if tv.install_path().join("Contents/Home").exists() {
this looks correct, though by default rtx will only add `~/.local/share/installs/java/*/bin` to PATH by default. You will need to modify that to `~/.local/share/installs/ava/*/Contents/Home/bin` by implementing `list_bin_paths()` (or a function named something almost exactly that). Similar to what you did for exec_env.

2023-08-28 13:29 UTC, jdx commented on src/plugins/core/java.rs
> +        if tv.install_path().join("Contents/Home").exists() {
I have some concerns here that people may be direct-linking their JDK in other places to `~/.local/share/rtx/installs/java/*` and we're moving that to a different place.

When I was thinking about this I was considering doing something like this instead:

```
ln -s ~/.local/share/rtx/installs/java/./Content/Home/* ~/.local/share/rtx/installs/java/./
```

that way we would merge the files and it would have the same structure as it does now but would also contain the files needed for macos integration

2023-08-28 13:30 UTC, jdx commented
thanks for taking this on, I have been looking at this over the past couple of weeks but have't found the time to work on it

2023-08-28 20:01 UTC, jdx reviewed
will try to test this myself probably tomorrow

2023-08-28 20:01 UTC, jdx commented on docs/java.md
> +ln -s ~/.local/share/rtx/installs/java/openjdk-20/Contents /Library/Java/JavaVirtualMachines/openjdk-20/Contents
needs sudo as well

2023-08-28 20:18 UTC, roele commented
Great thanks @jdx. 

Ran some manual tests with almost all distributions. Iberica does not ship with the required files and Zulu has the files but they're located in a different sub-folder (e.g. zulu-11.jdk). Added an addtional comment in the docs about that.

2023-08-29 19:04 UTC, jdx commented on src/plugins/core/java.rs
> +                "To enable macOS integration, run the following commands: \
make multiple calls to `info!()`, this is hard to read
<img width="901" alt="CleanShot 2023-08-29 at 14 04 21@2x" src="https://github.com/jdx/rtx/assets/216188/c3ba9fc1-6318-4b01-a374-0bbec68e5c25">

2023-08-29 20:56 UTC, roele commented on src/plugins/core/java.rs
> +                "To enable macOS integration, run the following commands: \
agree, the output is not optimal and mixes even different output types (progress message `java -version`).
you're probably right, package installation folders usually end in `.jdk` even though it also seems to work fine without.

2023-08-29 21:59 UTC, jdx commented on src/plugins/core/java.rs
> +                "To enable macOS integration, run the following commands:\n\
rust supports linebreaks inside of strings so you can just remove the end of these lines entirely

2023-08-29 22:06 UTC, roele commented on src/plugins/core/java.rs
> +                "To enable macOS integration, run the following commands:\n\
tried that, it interpreted the spaces in front of the commands

2023-08-29 22:37 UTC, jdx commented on src/plugins/core/java.rs
> +                "To enable macOS integration, run the following commands:\n\
oh! use indoc then, e.g.: https://github.com/jdx/rtx/blob/10647a97d7e05867549d77eb178aedadd128caa7/src/fake_asdf.rs#L22-L26

2023-08-30 02:18 UTC, merged